In [1]:
%run Pre-Processing.ipynb

In [2]:
%run Models.ipynb

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PowerTransformer
from imblearn.over_sampling import ADASYN
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.feature_selection import SelectKBest, f_classif
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.ensemble import RandomForestClassifier

In [5]:
SVM_selector(X_train_transformed, y_train, X_test_transformed, y_test)
KNN_Classifier(X_train_transformed, y_train, X_test_transformed, y_test)
RandomForest_Classifier(X_train_transformed, y_train, X_test_transformed, y_test)
LGBM_Classifier(X_train_transformed, y_train, X_test_transformed, y_test)
XGB_Classifier(X_train_transformed, y_train, X_test_transformed, y_test)
CatBoost_Classifier(X_train_transformed, y_train, X_test_transformed, y_test)

SVM Model:-
[LibSVM]

C:\Users\gauta\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Making predictions...

Classification Report:
              precision    recall  f1-score   support

      Normal     0.9368    0.9834    0.9596    103560
      Attack     0.2687    0.0840    0.1280      7496

    accuracy                         0.9227    111056
   macro avg     0.6027    0.5337    0.5438    111056
weighted avg     0.8917    0.9227    0.9034    111056


Confusion Matrix:
[[101845   1715]
 [  6866    630]]
KNN model
Classification Report:
              precision    recall  f1-score   support

      Normal     0.9352    0.9392    0.9372    103560
      Attack     0.1067    0.1003    0.1034      7496

    accuracy                         0.8826    111056
   macro avg     0.5209    0.5198    0.5203    111056
weighted avg     0.8792    0.8826    0.8809    111056

Confusion Matrix:
[[97262  6298]
 [ 6744   752]]
Random Forest:-


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   16.5s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  1.2min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  1.3min finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.7s
[Parallel(n_jobs=8)]: Done 200 out of 200 | elapsed:    0.8s finished


Classification Report:
              precision    recall  f1-score   support

      Normal     0.9985    0.8594    0.9238    103560
      Attack     0.3359    0.9825    0.5007      7496

    accuracy                         0.8677    111056
   macro avg     0.6672    0.9210    0.7122    111056
weighted avg     0.9538    0.8677    0.8952    111056

Confusion Matrix:
[[89002 14558]
 [  131  7365]]
LGBM Model:-
[LightGBM] [Info] Number of positive: 30200, number of negative: 414022
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.187768 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 16526
[LightGBM] [Info] Number of data points in the train set: 444222, number of used features: 79
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.067984 -> initscore=-2.618077
[LightGBM] [Info] Start training from score -2.618077
Classification Report:
              precision    recall  f1-score   support

      Normal 

0.9121943401030952

In [4]:
SVM_selector(X_train_resampled, y_train_resampled, X_test_transformed, y_test)
KNN_Classifier(X_train_resampled, y_train_resampled, X_test_transformed, y_test)
RandomForest_Classifier(X_train_resampled, y_train_resampled, X_test_transformed, y_test)
LGBM_Classifier(X_train_resampled, y_train_resampled, X_test_transformed, y_test)
XGB_Classifier(X_train_resampled, y_train_resampled, X_test_transformed, y_test)
CatBoost_Classifier(X_train_resampled, y_train_resampled, X_test_transformed, y_test)

SVM Model:-
[LibSVM]

C:\Users\gauta\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


Making predictions...

Classification Report:
              precision    recall  f1-score   support

      Normal     0.9368    0.9834    0.9596    103560
      Attack     0.2685    0.0840    0.1280      7496

    accuracy                         0.9227    111056
   macro avg     0.6027    0.5337    0.5438    111056
weighted avg     0.8917    0.9227    0.9034    111056


Confusion Matrix:
[[101844   1716]
 [  6866    630]]
KNN model
Classification Report:
              precision    recall  f1-score   support

      Normal     0.9393    0.9023    0.9204    103560
      Attack     0.1259    0.1944    0.1528      7496

    accuracy                         0.8545    111056
   macro avg     0.5326    0.5483    0.5366    111056
weighted avg     0.8844    0.8545    0.8686    111056

Confusion Matrix:
[[93442 10118]
 [ 6039  1457]]
Random Forest:-


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   21.9s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  1.8min finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.7s
[Parallel(n_jobs=8)]: Done 200 out of 200 | elapsed:    0.7s finished


Classification Report:
              precision    recall  f1-score   support

      Normal     0.9975    0.8612    0.9243    103560
      Attack     0.3359    0.9699    0.4990      7496

    accuracy                         0.8685    111056
   macro avg     0.6667    0.9155    0.7116    111056
weighted avg     0.9528    0.8685    0.8956    111056

Confusion Matrix:
[[89185 14375]
 [  226  7270]]
LGBM Model:-
[LightGBM] [Info] Number of positive: 83069, number of negative: 414022
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.144108 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 17246
[LightGBM] [Info] Number of data points in the train set: 497091, number of used features: 79
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.167110 -> initscore=-1.606248
[LightGBM] [Info] Start training from score -1.606248
Classification Report:
              precision    recall  f1-score   support

      Normal 

0.9220345561276013